### ISSUE TITLE
brightblack same as black?

### ISSUE THREAD

**Issue by singpolyma** [mordak/Term48#8]
I have one of my mutt colours set to "brightblack" which on most terminals shows as a sort of darkish gray. On term48 it shows the same as the black background and so is invisible.

**Comment by mordak** [comment]
Yes, Term48 supports 8 colours (following the qansi and / or xterm-color terminfo spec), but supporting more colours shouldn't be too hard. I'll have a look at xterm-16color and xterm-256color and see what I can come up with. If there isn't too much extra stuff in there then it should be straightforward to support.

**Comment by mordak** [comment]
Try version 0.4.1.2 in BB World (currently Draft, so go through the Developer menu). I think this one has the kinks worked out of many of the new features, and I implemented xterm-256color.

**Comment by singpolyma** [comment]
hmm, brightblack still showing same as black in my mutt. Also now my cyan band on the selected item seems to have a black chunk out of it

**Comment by singpolyma** [comment]
Your account on my server is active if that will maybe help :) Thanks for all your efforts!

**Comment by mordak** [comment]
Hmm.. I will have a look and see what's going on. Thanks!

**Comment by mordak** [comment]
Okay, mutt is sending SGR 0;1;30;40, which means bold black text on black background. I took a look at the suckless simple terminal, and they are rendering bold colours as the bright counterparts, which seems straightforward to do. Will try to get it sorted over the weekend.

**Comment by mordak** [comment]
And for the missing chunk from the top band there, this looks like a difference in the interpretation of EL. Mutt is sending EL (erase to end of line) after drawing the last character in the top menu. Term48 is literally erasing the rest of the line (setting NULL), but it looks like the expected norm is to maintain the current background colour. Should be not-too-hard to change the behaviour. Thanks!

**Comment by mordak** [comment]
Okay, 4.1.4 is up in Draft, and implements Bold => Bright, and EL uses the current style. vttest has some color tests (how did I not find these before?), and the EL/ED color tests are also passing.

**Comment by singpolyma** [comment]
awesome! working great!

**Comment by mordak** [comment]
Hooray! I am going to submit this version for Approval. Thank you for your efforts testing and patience with the intermediate builds. I really appreciate it. :-)

**Comment by HosseinHaida** [comment]
hey there, I'm new to the environment, what is the command to change the color to classic green on term48?

**Comment by mordak** [comment]
Changing the default text color is done through the .term48rc file. This is documented in the README in the discussion of the text_color preference, which should be set to [0, 255, 0] for green.

**Comment by HosseinHaida** [comment]
```
                                                                                  sorry, you actually meant here? (the pic in the attached file) Cause I can't reach [255, 255, 255] to edit                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: mordak‎Sent: Friday, April 22, 2016 01:48To: mordak/Term48Reply To: mordak/Term48Cc: CrackerJoe1; CommentSubject: Re: [mordak/Term48] brightblack same as black? (#8)Changing the default text color is done through the .term48rc file. This is documented in the README in the discussion of the text_color preference, which should be set to [0, 255, 0] for green.
```

—You are receiving this because you commented.Reply to this email directly or view it on GitHub

**Comment by HosseinHaida** [comment]
```
                                                                                  I also can't find the. Term48rc file anywhere on my passport BlackBerry, just confused                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: mordakSent: Friday, April 22, 2016 01:48To: mordak/Term48Reply To: mordak/Term48Cc: CrackerJoe1; CommentSubject: Re: [mordak/Term48] brightblack same as black? (#8)Changing the default text color is done through the .term48rc file. This is documented in the README in the discussion of the text_color preference, which should be set to [0, 255, 0] for green.
```

—You are receiving this because you commented.Reply to this email directly or view it on GitHub

**Comment by mordak** [comment]
This kind of support is best done over email. Please send me an email at mordak48@gmail.com and we can get you sorted.
